(function(){"use strict";
var shell=document.getElementById("sentinelShell"),launcher=document.getElementById("sentinelLauncher"),history=document.getElementById("sentinelHistory"),replies=document.getElementById("sentinelReplies"),form=document.getElementById("sentinelForm"),input=document.getElementById("sentinelInput"),access=document.getElementById("sentinelAccessNote"),previousFocus,briefStep=-1,briefAnswers=[];
if(!shell||!history||!form||!input)return;
/* Sentinel Core missions. They sit ahead of the general pathways so a mission
   prompt is never captured by a broader term, and every answer says what this
   public console cannot see rather than implying live telemetry. */
var missions=["Mission briefing","Risk assessment","Threat analysis","Infrastructure monitoring","AI governance","Executive intelligence"];
var pathways=[
{terms:["mission briefing","briefing","about clearglass","what does clearglass do"],answer:"ClearGlass Inc. is an Ontario practice that designs AI automation, agent systems, cybersecurity programs, legal-tech workflows, OSINT operations, and enterprise architecture for leaders who need speed without losing control. Consequential actions stay human-supervised, and every engagement starts with discovery rather than a pitch.",source:["Services & engagements","offers/index.html"],replies:["Risk assessment","AI governance","Talk to a human"]},
{terms:["risk assessment","risk","exposure","audit"],answer:"A ClearGlass risk assessment starts with what you own and who can reach it: identities, devices, cloud tenants, data flows, vendors, and the AI tools already in use, mapped against the controls you actually run. The low-commitment entry point is the Security Quick-Audit, a read-only posture review through a delegated least-privilege role. This console cannot scan or assess your systems itself.",source:["Security Quick-Audit","offers/security-quick-audit.html"],replies:["Threat analysis","View pricing","Talk to a human"]},
{terms:["threat analysis","threat model"],answer:"Sentinel has no access to your logs, alerts, or threat feeds, so it cannot tell you whether you are under attack. ClearGlass threat analysis is architecture-aware threat modeling: map how your systems, agentic AI, and suppliers could be abused, then rank the controls that close the likeliest paths first. If you believe an incident is in progress, contact your incident-response provider now and report it to the Canadian Centre for Cyber Security (cyber.gc.ca).",source:["Autonomous threat modeling","offers/autonomous-threat-modeling.html"],replies:["Infrastructure monitoring","Talk to a human","Start a project brief"]},
{terms:["infrastructure monitoring","monitoring","observability"],answer:"Sentinel is not connected to your infrastructure and does not monitor it. ClearGlass Managed Monitoring provides continuous exposure and attack-surface monitoring with monthly executive reporting. For your own stack, we design the telemetry, alert routing, runbooks, and least-privilege access that make monitoring trustworthy.",source:["Managed Monitoring","pricing.html"],replies:["AI governance","View pricing","Talk to a human"]},
{terms:["ai governance","governance","approval"],answer:"ClearGlass designs AI with governance in the architecture: bounded tool permissions, risk-scored actions, human approval gates before anything consequential, evaluations before release, and an append-only audit trail of who approved what and why. Low-risk work can run automatically; pricing, payments, credentials, and mass outreach wait for a named person.",source:["AI automation services","#services"],replies:["Executive intelligence","Start a project brief","Talk to a human"]},
{terms:["executive intelligence","intelligence brief","insights"],answer:"ClearGlass Insights publishes intelligence briefs on governed AI, cyber defence, and OSINT for decision-makers. Briefs are analysis, not live threat intelligence about your organisation; for a decision that affects you, ask for a human-reviewed briefing.",source:["ClearGlass Insights","blog/"],replies:["Mission briefing","Talk to a human","Start a project brief"]},
{terms:["website","web design","performance"],answer:"A high-performance website pathway usually starts with a content and conversion audit, then information architecture, accessible interface design, implementation, and measured launch validation.",source:["Web design service","web-design.html"],replies:["What platform do you use?","Start a project brief","Talk to a human"]},
{terms:["lead","seo","growth"],answer:"For qualified growth, ClearGlass can connect positioning, technical SEO, conversion paths, analytics, and responsible automation. We first identify the audience and meaningful conversion—without inventing traffic or outcome guarantees.",source:["Services & engagements","offers/index.html"],replies:["Who are your ideal users?","Start a project brief","View services"]},
{terms:["ai","automation","agent"],answer:"The AI automation pathway maps the workflow, data boundaries, model and tool permissions, evaluations, approval gates, observability, and rollback before production enablement. Consequential actions remain human-supervised.",source:["AI automation services","#services"],replies:["What workflow should improve?","How do approval gates work?","Start a project brief"]},
{terms:["portal","application","app"],answer:"A secure portal engagement begins with user roles, data classification, tenant boundaries, authentication, authorization, audit requirements, and the smallest useful workflow. Interface restrictions alone are never treated as authorization.",source:["ClearGlass capabilities","#services"],replies:["Who will use the portal?","What integrations are needed?","Start a project brief"]},
{terms:["cyber","security","incident","alert","threat"],answer:"ClearGlass provides blue-team-aligned cybersecurity guidance: risk and control mapping, exposure reduction, detection priorities, zero-trust architecture, and incident readiness. This public concierge cannot inspect systems or confirm an incident; sensitive or urgent matters should be escalated to an authorized human.",source:["Cybersecurity & risk","#services"],replies:["Talk to a human","How is sensitive data handled?","Start a project brief"]},
{terms:["cloud","deploy","devops","hosting"],answer:"A cloud deployment pathway covers workload boundaries, CI/CD controls, least-privilege identity, environment protection, observability, recovery, and rollback. Recommendations depend on your stack, availability needs, and compliance constraints.",source:["Enterprise architecture","#services"],replies:["What stack do you use?","What uptime do you need?","Start a project brief"]},
{terms:["price","cost","budget"],answer:"I will not invent pricing or availability. Approved engagement information is on the pricing and services pages, and a human can confirm a scoped estimate after discovery.",source:["Published pricing","pricing.html"],replies:["View pricing","Talk to a human","Start a project brief"]}
];
var questions=["What are you trying to build or improve?","What does your current website or platform use?","What is the main business goal, and who are the users?","What integrations are required?","What timeline are you considering?","Which constraints matter most—budget, performance, accessibility, privacy, security, or compliance?","Do you need ongoing support, and what level of security or compliance review is expected?"];
function addMessage(text,actor,source){var item=document.createElement("article"),avatar=document.createElement("span"),body=document.createElement("div"),copy=document.createElement("p");item.className="sentinel-message sentinel-message--"+actor;avatar.className="sentinel-message-avatar";avatar.setAttribute("aria-hidden","true");avatar.textContent=actor==="user"?"YOU":"S";body.className="sentinel-message-body";copy.textContent=text;body.appendChild(copy);if(actor==="assistant"){var meta=document.createElement("div");meta.className="sentinel-message-meta";meta.appendChild(document.createTextNode("Confidence: "+(source?"High":"General guidance")+" · Source: "));if(source){var link=document.createElement("a");link.href=source[1];link.textContent=source[0];meta.appendChild(link)}else meta.appendChild(document.createTextNode("Sentinel policy"));body.appendChild(meta)}item.append(avatar,body);history.appendChild(item);history.scrollTop=history.scrollHeight}
/* Terms match from the start of a word, and short terms (ai, app, seo) only as
   whole words, so "email" is not an AI question and "approval" is not a portal. */
function hasTerm(text,term){var esc=term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp("(^|[^a-z0-9])"+esc+(term.length<=3?"s?(?![a-z0-9])":""),"i").test(text)}
function setReplies(labels){replies.replaceChildren();labels.forEach(function(label){var button=document.createElement("button");button.type="button";button.textContent=label;button.addEventListener("click",function(){handleMessage(label)});replies.appendChild(button)})}
function welcome(){if(history.children.length)return;addMessage("Sentinel Core online. I’m ClearGlass Sentinel, an automated, rule-guided concierge. I can brief you on ClearGlass, map a project pathway, or connect you with a human. I cannot access systems or activate support and blue-team modes from this public page. Choose a mission or tell me what you want to strengthen.","assistant");setReplies(["Mission briefing","Explore services","Cybersecurity guidance","Start a project brief","Talk to a human"])}
function openPanel(prompt){var link=panelScope().querySelector("[data-sentinel-link]");if(link)link.textContent=(navigator.onLine===false?"Offline":"Online")+" · Active · Ready";if(hero)hero.dataset.sentinelState="open-idle";previousFocus=document.activeElement;shell.hidden=false;document.body.classList.add("sentinel-open");welcome();shell.querySelector("[data-sentinel-close]").focus();if(prompt)handleMessage(prompt)}
function closePanel(){stopVoice();if(hero)hero.dataset.sentinelState="closed";shell.hidden=true;document.body.classList.remove("sentinel-open");if(previousFocus&&previousFocus.focus)previousFocus.focus()}
function startBrief(){briefStep=0;briefAnswers=[];addMessage("Let’s create a private draft in this browser. Please do not include credentials or sensitive records. "+questions[0],"assistant");setReplies(["I need a website","I need automation","I need security guidance"])}
function continueBrief(message){briefAnswers.push(message);briefStep++;if(briefStep<questions.length){addMessage(questions[briefStep],"assistant");setReplies(["Skip this question","Talk to a human"])}else{addMessage("Your draft brief is ready. Nothing has been submitted. Review it, remove sensitive details, then choose “Talk to a human” to contact ClearGlass and explicitly decide what to share.","assistant");setReplies(["Talk to a human","Clear conversation","Explore services"])}}
function handleMessage(raw){var message=String(raw||"").trim().slice(0,800);if(!message)return;addMessage(message,"user");var normalized=message.toLowerCase();if(/password|api[ -]?key|secret key|credit card|card number|private key|credential/.test(normalized)){addMessage("Please do not share that information. I have not transmitted or stored this conversation. Remove sensitive data and contact an authorized ClearGlass human through a verified channel if support is required.","assistant");setReplies(["Talk to a human","Clear conversation"]);return}if(normalized.includes("talk to a human")){addMessage("Use the “Talk to a human” link below to open your email client. You choose what to send; Sentinel does not submit this conversation automatically.","assistant");setReplies(["Start a project brief","Explore services"]);return}if(normalized.includes("clear conversation")){history.replaceChildren();replies.replaceChildren();briefStep=-1;briefAnswers=[];welcome();return}if(briefStep>=0){continueBrief(message);return}if(normalized.includes("start a project brief")){startBrief();return}if(normalized.includes("view pricing")){location.href="pricing.html";return}if(normalized.includes("view services")||normalized==="explore services"){location.href="offers/index.html";return}var match=pathways.find(function(p){return p.terms.some(function(term){return hasTerm(normalized,term)})});if(match){addMessage(match.answer,"assistant",match.source);setReplies(match.replies);return}addMessage("I can help with web design, web applications, AI automation, cybersecurity, DevOps, SEO, cloud deployment, and governed growth infrastructure. For legal, financial, sensitive, or incident-specific decisions, I will route you to a human rather than guess.","assistant");setReplies(["Explore services","Start a project brief","Talk to a human"])}
function onClick(sel,fn,root){var el=(root||document).querySelector(sel);if(el)el.addEventListener("click",fn);return el}
function clearConversation(){history.replaceChildren();replies.replaceChildren();briefStep=-1;briefAnswers=[];welcome()}
/* Input modes. Voice is dictation only: the transcript lands in the composer for
   review and is never sent automatically, so the sensitive-data guard in
   handleMessage still runs on everything that is sent. */
var VoiceRecognition=window.SpeechRecognition||window.webkitSpeechRecognition,recognizer=null;
var voiceCopy={ready:"Voice uses your browser’s speech recognition, which your browser provider may process. ClearGlass receives nothing. Review the transcript, then send.",unsupported:"Voice input is not available in this browser. Your keyboard’s dictation key still works in Text mode.",denied:"Microphone access was declined, so voice input is off. Text mode still works."};
function panelScope(){return shell.querySelector(".sentinel-panel")||shell}
function voiceNote(key){var note=panelScope().querySelector("[data-sentinel-voice-note]");if(note)note.textContent=voiceCopy[key]}
function resetMic(){recognizer=null;var mic=panelScope().querySelector("[data-sentinel-voice]");if(mic){mic.setAttribute("aria-pressed","false");mic.setAttribute("aria-label","Start voice input");mic.classList.remove("is-listening")}}
function stopVoice(){var active=recognizer;resetMic();if(active){try{active.abort()}catch(e){}}}
function toggleVoice(){if(recognizer){stopVoice();return}if(!VoiceRecognition||!input)return;var mic=panelScope().querySelector("[data-sentinel-voice]"),base=input.value.trim()?input.value.trim()+" ":"",session;try{session=new VoiceRecognition()}catch(e){voiceNote("unsupported");return}session.lang=document.documentElement.lang||"en";session.interimResults=true;session.continuous=false;session.onresult=function(event){var heard="";for(var i=0;i<event.results.length;i++)heard+=event.results[i][0].transcript;input.value=(base+heard).slice(0,800)};session.onerror=function(event){if(event&&(event.error==="not-allowed"||event.error==="service-not-allowed"))voiceNote("denied")};session.onend=function(){if(recognizer!==session)return;resetMic();if(input)input.focus()};recognizer=session;if(mic){mic.setAttribute("aria-pressed","true");mic.setAttribute("aria-label","Stop voice input");mic.classList.add("is-listening")}try{session.start()}catch(e){resetMic()}}
function setMode(mode){var scope=panelScope(),mic=scope.querySelector("[data-sentinel-voice]"),note=scope.querySelector("[data-sentinel-voice-note]");scope.querySelectorAll("[data-sentinel-mode]").forEach(function(b){b.setAttribute("aria-pressed",String(b.dataset.sentinelMode===mode))});if(mode!=="voice")stopVoice();if(mic)mic.hidden=mode!=="voice"||!VoiceRecognition;if(note){note.hidden=mode!=="voice";voiceNote(VoiceRecognition?"ready":"unsupported")}if(input)input.placeholder=mode==="query"?"Choose a mission or state an objective…":"Describe what you want to build or improve…";if(mode==="query")setReplies(missions);else if(input&&mode==="text")input.focus()}
function bindPanel(){
  var scope=shell.querySelector(".sentinel-panel")||shell;
  history=scope.querySelector("#sentinelHistory")||history;
  replies=scope.querySelector("#sentinelReplies")||replies;
  form=scope.querySelector("#sentinelForm")||form;
  input=scope.querySelector("#sentinelInput")||input;
  shell.querySelectorAll("[data-sentinel-close]").forEach(function(b){if(!b.__cgBound){b.__cgBound=true;b.addEventListener("click",closePanel)}});
  onClick("[data-sentinel-access]",function(){if(access)access.hidden=!access.hidden},scope);
  onClick("[data-sentinel-brief]",startBrief,scope);
  onClick("[data-sentinel-clear]",clearConversation,scope);
  scope.querySelectorAll("[data-sentinel-mode]").forEach(function(b){if(!b.__cgBound){b.__cgBound=true;b.addEventListener("click",function(){setMode(b.dataset.sentinelMode)})}});
  var mic=scope.querySelector("[data-sentinel-voice]");if(mic&&!mic.__cgBound){mic.__cgBound=true;mic.addEventListener("click",toggleVoice)}
  if(form&&!form.__cgBound){form.__cgBound=true;form.addEventListener("submit",function(e){e.preventDefault();if(hero)hero.dataset.sentinelState="processing";var message=input?input.value:"";if(input)input.value="";handleMessage(message);if(hero)hero.dataset.sentinelState="response-ready"})}
  if(input&&!input.__cgBound){input.__cgBound=true;input.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}})}
}
document.querySelectorAll("[data-sentinel-open]").forEach(function(b){b.addEventListener("click",function(){openPanel()})});document.querySelectorAll("[data-sentinel-prompt]").forEach(function(b){b.addEventListener("click",function(){openPanel(b.dataset.sentinelPrompt)})});onClick("[data-sentinel-dismiss]",function(){if(launcher)launcher.hidden=true;try{sessionStorage.setItem("cg-sentinel-dismissed","true")}catch(e){}});bindPanel();
window.__cgSentinelRebind=bindPanel;
var hero=document.querySelector(".sentinel-hero"),recommendation=hero&&hero.querySelector("[data-sentinel-recommendation]"),pathwayLabel=hero&&hero.querySelector("[data-sentinel-pathway]"),reasonLabel=hero&&hero.querySelector("[data-sentinel-reason]"),sessionLabels=document.querySelectorAll("[data-sentinel-session]");
var visualFlags={proceduralNeon:true,vectorInstrumentation:true,pointerEnergy:true,advancedGlass:true,gpuField:false,telemetryRail:true};
var recommendationRules={
"I need a high-performance website.":["High-performance web systems","Performance, accessibility, conversion architecture, and measured launch validation."],
"I want more qualified leads.":["Digital growth systems","Positioning, technical SEO, responsible automation, and observable conversion paths."],
"I need AI automation.":["ClearGlass AI systems","Workflow architecture, bounded tools, evaluations, human approval, and rollback."],
"I need a secure customer portal.":["Secure application engineering","Identity, tenant boundaries, server-side authorization, and audit-ready workflows."],
"I need cybersecurity guidance.":["Cybersecurity and risk","Zero-trust architecture, control assurance, exposure reduction, and incident readiness."],
"I need cloud deployment help.":["Cloud and deployment architecture","Least-privilege delivery, protected environments, observability, recovery, and rollback."],
"I want a full digital growth system.":["Governed digital operating system","Integrated web, growth, automation, measurement, and human-controlled execution."]};
function createSessionId(){var bytes=new Uint8Array(2);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(bytes);else{bytes[0]=Math.floor(Math.random()*256);bytes[1]=Math.floor(Math.random()*256)}return "CG-SNT-"+Array.from(bytes,function(value){return value.toString(16).padStart(2,"0")}).join("").toUpperCase()}
var sessionId=createSessionId();sessionLabels.forEach(function(label){label.textContent="SESSION "+sessionId});
if(hero){hero.querySelectorAll("[data-sentinel-prompt]").forEach(function(button){button.setAttribute("aria-pressed","false");button.addEventListener("click",function(){hero.querySelectorAll("[data-sentinel-prompt]").forEach(function(item){item.setAttribute("aria-pressed",String(item===button))});var match=recommendationRules[button.dataset.sentinelPrompt];if(match&&recommendation){pathwayLabel.textContent=match[0];reasonLabel.textContent=match[1];recommendation.hidden=false;hero.dataset.sentinelState="response-ready"}})});var inspectorCopy={session:"<strong>SESSION</strong><br>Ephemeral UI correlation: "+sessionId+". No database identifier is exposed.",system:"<strong>SYSTEM</strong><br>Mode: PUBLIC &nbsp; Provider: DEMO &nbsp; External tools: DISABLED",capabilities:"<strong>CAPABILITIES</strong><br>Public product guidance · Project discovery · Service mapping · Draft brief · Human handoff",privacy:"<strong>PRIVACY</strong><br>Browser-only preview. Do not enter credentials, payment information, private records, or secret documents."};hero.querySelectorAll("[data-sentinel-inspector]").forEach(function(button){button.addEventListener("click",function(){var panel=hero.querySelector("[data-sentinel-inspector-panel]"),open=button.getAttribute("aria-expanded")==="true";hero.querySelectorAll("[data-sentinel-inspector]").forEach(function(item){item.setAttribute("aria-expanded","false")});button.setAttribute("aria-expanded",String(!open));panel.hidden=open;if(!open)panel.innerHTML=inspectorCopy[button.dataset.sentinelInspector]})})}
function SentinelVisualRuntime(root,flags){this.root=root;this.flags=flags;this.frame=0;this.visible=true;this.last=0;this.motion=window.matchMedia("(prefers-reduced-motion: reduce)");this.pointerFrame=0}
SentinelVisualRuntime.prototype.start=function(){var runtime=this;if(!this.root||this.motion.matches||!this.flags.proceduralNeon)return;this.observer=new IntersectionObserver(function(entries){runtime.visible=entries[0].isIntersecting});this.observer.observe(this.root);this.visibility=function(){runtime.visible=!document.hidden};document.addEventListener("visibilitychange",this.visibility);if(this.flags.pointerEnergy&&window.matchMedia("(pointer:fine)").matches)this.root.addEventListener("pointermove",this.onPointerMove=function(event){if(runtime.pointerFrame)return;runtime.pointerFrame=requestAnimationFrame(function(){var box=runtime.root.getBoundingClientRect();runtime.root.style.setProperty("--cg-energy-x",((event.clientX-box.left)/box.width*100).toFixed(1)+"%");runtime.root.style.setProperty("--cg-energy-y",((event.clientY-box.top)/box.height*100).toFixed(1)+"%");runtime.pointerFrame=0})});function tick(now){runtime.frame=requestAnimationFrame(tick);if(!runtime.visible||now-runtime.last<33)return;runtime.last=now;var t=now/1000,intensity=.82+Math.sin(t*.66)*.10+Math.sin(t*.19+1.4)*.05+Math.cos(t*.043)*.025,hue=188+Math.sin(t*.075)*7+Math.sin(t*.018)*3;runtime.root.style.setProperty("--cg-neon-intensity",intensity.toFixed(3));runtime.root.style.setProperty("--cg-neon-hue",hue.toFixed(2));runtime.root.style.setProperty("--cg-border-angle",((t*9)%360).toFixed(1)+"deg")}this.frame=requestAnimationFrame(tick)};
var showChat=null;
var visualRuntime=new SentinelVisualRuntime(hero,visualFlags);try{visualRuntime.start()}catch(error){if(hero)hero.dataset.visualQuality="static"}
shell.addEventListener("keydown",function(e){if(e.key==="Escape"){closePanel();return}if(e.key!=="Tab")return;var all=Array.from(shell.querySelectorAll("button,a[href],textarea")).filter(function(el){return el.offsetParent!==null});if(!all.length)return;var first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});try{if(sessionStorage.getItem("cg-sentinel-dismissed")==="true")launcher.hidden=true}catch(e){}

/* ClearGlass Station — advanced homepage navigation layer.
   The existing Sentinel concierge remains intact; the launcher now opens
   a navigable command-station surface first. No backend, tracking, or
   external command execution is introduced. */
(function(){
  var panel=shell.querySelector(".sentinel-panel");
  if(!panel||!launcher)return;
  var originalPanelHTML=panel.innerHTML;
  var stationHTML='<header class="sentinel-panel-header"><div class="sentinel-brand"><span class="sentinel-mark" aria-hidden="true">CG</span><span><small>ClearGlass Inc.</small><strong>CLEARGLASS STATION</strong></span></div><button type="button" class="sentinel-icon-button" data-station-close aria-label="Close ClearGlass Station">×</button></header>'+
  '<div class="sentinel-modebar"><div><span class="sentinel-live-dot" aria-hidden="true"></span><strong>Navigation command layer</strong><small>PUBLIC SURFACE · LOCAL ROUTING · NO EXTERNAL ACTIONS</small></div><button type="button" data-station-chat>ASK SENTINEL</button></div>'+
  '<div class="cg-station-body">'+
  '<div class="cg-station-kicker">MISSION CONTROL / SITE DIRECTORY</div><h2>Where do you want to go?</h2><p class="cg-station-sub">Move directly between ClearGlass services, intelligence surfaces, products, systems, and contact pathways.</p>'+
  '<div class="cg-station-grid" role="navigation" aria-label="ClearGlass Station navigation">'+
  '<a class="cg-station-item cg-station-primary" href="index.html"><span class="cg-station-code">00</span><span><strong>Command Home</strong><small>ClearGlass Inc. homepage and operating overview</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="offers/index.html"><span class="cg-station-code">01</span><span><strong>Services &amp; Engagements</strong><small>AI, cybersecurity, automation, architecture and growth</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="pricing.html"><span class="cg-station-code">02</span><span><strong>Pricing &amp; Engagements</strong><small>Published commercial pathways and scope</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="products.html"><span class="cg-station-code">03</span><span><strong>Product Systems</strong><small>ClearGlass platforms, products and intelligence surfaces</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="systems.html"><span class="cg-station-code">04</span><span><strong>Systems Command</strong><small>ARTEMIS, PERCIVAL and advanced ClearGlass systems</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="CG-os.html"><span class="cg-station-code">05</span><span><strong>ClearGlass OS</strong><small>Command-center and operating-system surfaces</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="agentmesh.html"><span class="cg-station-code">06</span><span><strong>Agent Mesh</strong><small>Orchestration, automation and agent architecture</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="conduit.html"><span class="cg-station-code">07</span><span><strong>CONDUIT</strong><small>Workflow automation and integration architecture</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="artemis.html"><span class="cg-station-code">08</span><span><strong>ARTEMIS</strong><small>Autonomous intelligence and governed execution</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="command-center.html"><span class="cg-station-code">09</span><span><strong>Command Center</strong><small>Executive security operations surface</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="blog/"><span class="cg-station-code">10</span><span><strong>Insights</strong><small>Research, intelligence briefs and strategic analysis</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="store.html"><span class="cg-station-code">11</span><span><strong>Store</strong><small>Digital products and ClearGlass offerings</small></span><b>→</b></a>'+
  '<a class="cg-station-item" href="contact.html"><span class="cg-station-code">12</span><span><strong>Contact / Human Handoff</strong><small>Move from automated discovery to a human conversation</small></span><b>→</b></a>'+ 
  '</div>'+
  '<div class="cg-station-footer"><span>ROUTING: LOCAL</span><span>STATUS: READY</span><span>SESSION: '+sessionId+'</span></div></div>';
  showChat=function(){if(!panel.classList.contains("cg-station-active"))return;panel.innerHTML=originalPanelHTML;panel.classList.remove("cg-station-active");window.__cgSentinelRebind()};
  function openStation(){
    stopVoice();
    panel.innerHTML=stationHTML;
    panel.classList.add("cg-station-active");
    var close=panel.querySelector("[data-station-close]");
    if(close)close.addEventListener("click",closePanel);
    var chat=panel.querySelector("[data-station-chat]");
    if(chat)chat.addEventListener("click",function(){showChat();welcome();var f=panel.querySelector("#sentinelInput");if(f)f.focus();});
    var first=panel.querySelector("a,button");if(first)first.focus();
  }
  var stationOpeners=Array.prototype.slice.call(document.querySelectorAll("[data-sentinel-open]"));if(launcher&&stationOpeners.indexOf(launcher)<0)stationOpeners.push(launcher);var stationQueued=false;function queueStation(){if(stationQueued)return;stationQueued=true;setTimeout(function(){stationQueued=false;openStation()},0)}stationOpeners.forEach(function(el){el.addEventListener("click",queueStation)});
  shell.addEventListener("click",function(e){var link=e.target.closest&&e.target.closest(".cg-station-item");if(link){panel.classList.add("cg-station-routing");}}
  );
})();

/* Sentinel Core hand-off. The dock opens the conversation itself, never the
   directory above: [data-sentinel-open] clicks still route to the Station
   first, so other surfaces keep that behaviour. A mission sent mid-brief
   abandons the draft rather than being recorded as an answer to it. */
function openChat(prompt){if(showChat)showChat();if(prompt&&briefStep>=0){briefStep=-1;briefAnswers=[]}openPanel(prompt);if(!prompt&&input){try{input.focus({preventScroll:true})}catch(e){input.focus()}}}
window.__cgSentinel={open:function(){openChat()},ask:function(prompt){openChat(String(prompt||"").trim().slice(0,800)||undefined)},missions:missions.slice(),session:sessionId};
}());
