'use client';

import {useMemo, useState} from 'react';

const nav=['COMMAND','PROJECTS','CAD','PHYSICS','SYSTEMS','CONTROLS','DIGITAL TWIN','AI OPTIMIZER','MANUFACTURING','REQUIREMENTS','VERIFICATION','COMPLIANCE','DATA','REPORTS','ADMIN'];
const agents=['CAD AGENT','PHYSICS AGENT','SYSTEMS AGENT','CONTROL AGENT','OPTIMIZATION AGENT','MANUFACTURING AGENT','VERIFICATION AGENT','COMPLIANCE AGENT','REPORTING AGENT'];
const requirements=[['REQ-001','Payload capacity','Support 2 kg payload','SIMULATION','NOT TESTED'],['REQ-002','Structural safety','Meet configured safety factor','SIMULATION','PASS'],['REQ-003','Manufacturability','Compatible with additive/CNC process','REVIEW','BLOCKED'],['REQ-004','Energy efficiency','Optimize propulsion energy','TEST','NOT TESTED']];

function Status({children}:{children:string}){return <span className={'status '+children.toLowerCase().replaceAll(' ','-')}>{children}</span>}

export default function Artemis(){
 const [active,setActive]=useState('COMMAND'); const [copilot,setCopilot]=useState(''); const [notice,setNotice]=useState('');
 const data=useMemo(()=>({activeProjects:3,running:2,failed:1,iterations:18,opt:4,coverage:76,manufacturing:64,compliance:91}),[]);
 const run=(msg:string)=>{setNotice(msg);setTimeout(()=>setNotice(''),3200)};
 return <main className="os">
  <aside className="rail">
   <div className="brand"><div className="mark">A</div><div><strong>ARTEMIS</strong><small>ENGINEERING / UEIP</small></div></div>
   <div className="rail-section">WORKSPACE</div>
   <nav>{nav.map((n,i)=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><span className="idx">{String(i+1).padStart(2,'0')}</span>{n}</button>)}</nav>
   <div className="rail-footer"><div className="live-dot"/> SYSTEM ONLINE<br/><small>UEIP CORE · DEMO MODE</small></div>
  </aside>
  <section className="surface">
   <header className="topbar"><div className="crumb">ARTEMIS / <b>{active}</b></div><div className="search">⌕ <input placeholder="Search engineering data…" onKeyDown={e=>{if(e.key==='Enter')run('Search indexed across projects, models, evidence and reports.')}}/></div><div className="signals"><span>SIM <b>2 RUN</b></span><span>CPU <b>42%</b></span><span>AI <b>9/9</b></span><span>VER <b>76%</b></span><button onClick={()=>run('Command palette: /project /cad /simulate /optimize /requirements /verify /report /copilot')}>⌘K</button></div></header>
   <div className="workspace">
    <div className="title-row"><div><div className="eyebrow">UNIFIED ENGINEERING INTELLIGENCE PLATFORM</div><h1>{active==='COMMAND'?'Engineering Command Center':active}</h1><p>ARTEMIS UAV · Lightweight Autonomous Drone <Status>DEMO DATA</Status></p></div><div className="actions"><button onClick={()=>run('New engineering revision initialized.')}>+ NEW REVISION</button><button className="primary" onClick={()=>run('Simulation job queued. No certified solver result has been generated.')}>RUN SIMULATION</button></div></div>
    {active==='COMMAND' ? <>
     <section className="metrics">{[['ACTIVE PROJECTS',data.activeProjects,'+1'],['RUNNING SIMULATIONS',data.running,'LIVE'],['FAILED SIMULATIONS',data.failed,'ATTENTION'],['DESIGN ITERATIONS',data.iterations,'v0.18'],['OPTIMIZATION JOBS',data.opt,'QUEUED'],['REQ COVERAGE',data.coverage+'%','TRACE']].map(([a,b,c])=><article key={String(a)}><label>{a}</label><strong>{b}</strong><em>{c}</em></article>)}</section>
     <section className="grid-main">
      <article className="panel viewport"><div className="panel-head"><div><label>CAD / DIGITAL TWIN VIEW</label><h2>UAV Structural Assembly</h2></div><span>REV 18 · SIMULATION READY</span></div><div className="cad-scene"><div className="grid-floor"/><svg viewBox="0 0 800 390" role="img" aria-label="Demo UAV engineering assembly"><g fill="none" stroke="currentColor" strokeWidth="2"><ellipse cx="400" cy="190" rx="155" ry="52"/><rect x="315" y="155" width="170" height="70" rx="8"/><path d="M315 175L165 110M315 205L165 270M485 175L635 110M485 205L635 270"/><circle cx="155" cy="105" r="42"/><circle cx="645" cy="105" r="42"/><circle cx="155" cy="275" r="42"/><circle cx="645" cy="275" r="42"/><path d="M345 155V105M455 155V105M345 225V275M455 225V275"/></g><g fill="currentColor" opacity=".35"><circle cx="400" cy="190" r="28"/><circle cx="155" cy="105" r="14"/><circle cx="645" cy="105" r="14"/><circle cx="155" cy="275" r="14"/><circle cx="645" cy="275" r="14"/></g></svg><div className="axis">X 0.000 · Y 0.000 · Z 0.000<br/>MM · WORLD CSYS</div></div></article>
      <article className="panel copilot"><div className="panel-head"><div><label>AI ENGINEERING COPILOT</label><h2>Mission Assistant</h2></div><Status>GOVERNED</Status></div><div className="copilot-body"><p className="ai-intro">I can reason over requirements, CAD metadata, simulation configuration, verification evidence and revisions.</p><div className="prompt"><textarea value={copilot} onChange={e=>setCopilot(e.target.value)} placeholder="Ask an engineering question…"/><button onClick={()=>run(copilot?`Copilot queued analysis: ${copilot}`:'Enter an engineering question.')}>RUN ↗</button></div><div className="plan"><div className="plan-head">EXAMPLE MISSION PLAN <span>10 STEPS</span></div>{['Requirements','Geometry proposal','Material candidates','Load cases','Boundary conditions','Mesh strategy','Simulation plan','Optimization','Manufacturability','Verification'].map((x,i)=><div className="plan-row" key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}<span>READY</span></div>)}</div></div></article>
     </section>
     <section className="grid-bottom"><article className="panel"><div className="panel-head"><div><label>REQUIREMENTS TRACEABILITY</label><h2>Engineering Evidence Matrix</h2></div><button onClick={()=>setActive('REQUIREMENTS')}>OPEN MATRIX →</button></div><table><thead><tr><th>ID</th><th>REQUIREMENT</th><th>METHOD</th><th>STATUS</th></tr></thead><tbody>{requirements.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]} — {r[2]}</td><td>{r[3]}</td><td><Status>{r[4]}</Status></td></tr>)}</tbody></table></article><article className="panel"><div className="panel-head"><div><label>AGENT ORCHESTRATOR</label><h2>Engineering Agents</h2></div><Status>9 ONLINE</Status></div><div className="agents">{agents.map((a,i)=><div key={a}><span className="agent-dot"/><b>{a}</b><small>{i%3===0?'IDLE':i%3===1?'READY':'MONITORING'}</small></div>)}</div></article></section>
    </> : <Module name={active} run={run}/>} 
   </div>
   <footer className="statusbar"><span>PROJECT <b>ARTEMIS UAV</b></span><span>MODEL <b>v0.18</b></span><span>SIM <b>RUNNING ×2</b></span><span>SOLVER <b>ADAPTER / DEMO</b></span><span>CPU <b>42%</b></span><span>UNITS <b>MM · KG · N</b></span><span>CSYS <b>WORLD</b></span><span>AUDIT <b>ENABLED</b></span></footer>
  </section>{notice&&<div className="toast">{notice}</div>}
 </main>
}

function Module({name,run}:{name:string;run:(s:string)=>void}){const map:Record<string,string[]>= {CAD:['3D viewport','Model tree','Feature tree','Assemblies','Sketches','Constraints','Materials','BOM'],PHYSICS:['Structural / FEA','Thermal','CFD','Electromagnetics','Battery','Mesh','Boundary Conditions','Solver Provenance'],SYSTEMS:['Block diagram','Sensor','Actuator','Plant','Signal Flow','Subsystems','Validation'],CONTROLS:['PID','State Space','Feedback','Scopes','Parameters','Simulation'], 'DIGITAL TWIN':['Asset health','Telemetry','Temperature','Vibration','Pressure','Energy','Failure forecast'], 'AI OPTIMIZER':['Objective','Constraints','Baseline','Candidates','Pareto frontier','Tradeoffs'],MANUFACTURING:['CNC','Additive','Injection molding','Sheet metal','Robotics','Assembly','Inspection'],REQUIREMENTS:['Requirements','Traceability','Verification methods','Evidence','Approvals','Coverage'],VERIFICATION:['PASS','FAIL','BLOCKED','NOT TESTED','WAIVED','Evidence matrix'],COMPLIANCE:['Governance','Audit events','AI decisions','Approvals','Provenance','Certification state'],DATA:['Models','Results','Telemetry','Artifacts','Versions','Provenance'],REPORTS:['Design Review','Simulation Report','Verification','Manufacturing Readiness','Digital Twin Health','Compliance','Executive Summary'],ADMIN:['Users','Roles','Project isolation','Audit policy','Adapters','System health'],PROJECTS:['ARTEMIS UAV','Design library','Simulation jobs','Revisions','Evidence']}; const items=map[name]||['Workspace']; return <div className="module"><div className="module-hero"><div><div className="eyebrow">ARTEMIS ENGINEERING WORKSPACE</div><h2>{name}</h2><p>Functional engineering workspace with governed state, traceability and adapter-ready architecture.</p></div><button className="primary" onClick={()=>run(`${name} workspace action queued.`)}>CREATE JOB</button></div><div className="module-grid">{items.map((x,i)=><article className="module-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{name==='PHYSICS'?'Solver-backed results require an actual validated adapter.':name==='COMPLIANCE'?'Evidence and provenance remain attached to every decision.':'Ready for engineering workflow configuration.'}</p><button onClick={()=>run(`${x}: workspace opened.`)}>OPEN →</button></article>)}</div><div className="safety"><b>ENGINEERING STATE CONTROL</b><span>PROTOTYPE</span><span>SIMULATION</span><span>VALIDATED</span><span>VERIFIED</span><span>CERTIFIED</span><small>Demo interface never upgrades a result to certified status without validated evidence and qualified review.</small></div></div>}
