from __future__ import annotations

from .models import SourceDefinition


def _s(
    source_id: str,
    name: str,
    categories: list[str],
    integration_mode: str,
    public_api: str,
    authentication: str,
    rate_limit: str,
    license: str,
    terms_concern: str,
    metadata: list[str],
    update_frequency: str,
    ingestion_method: str,
    value: str,
    risk_level: str,
    reliability: int,
    complexity: str,
    effort_days: str,
    phase: int,
    *,
    endpoint: str | None = None,
    auth_env: str | None = None,
    rate_limit_rps: float | None = None,
    adapter: str = "http_json",
    enabled: bool = False,
) -> SourceDefinition:
    return SourceDefinition(
        source_id=source_id,
        name=name,
        categories=categories,
        integration_mode=integration_mode,
        public_api=public_api,
        authentication=authentication,
        auth_env=auth_env,
        rate_limit=rate_limit,
        rate_limit_rps=rate_limit_rps,
        license=license,
        terms_concern=terms_concern,
        metadata=metadata,
        update_frequency=update_frequency,
        ingestion_method=ingestion_method,
        endpoint=endpoint,
        adapter=adapter,
        value=value,
        risk_level=risk_level,
        integration_reliability_score=reliability,
        integration_complexity=complexity,
        effort_days=effort_days,
        phase=phase,
        enabled_by_default=enabled,
    )


SOURCE_DEFINITIONS: tuple[SourceDefinition, ...] = (
    _s("zoom-earth", "Zoom Earth", ["Real-Time Geospatial", "Weather", "Earth Observation"],
        "web_only", "No general public API verified", "None", "Not published; do not automate at scale",
        "Provider/content-specific; verify before reuse", "Web interaction is subject to provider ToS; no scraping",
        ["map imagery", "weather overlays", "storm tracks"], "near-real-time",
        "deep-link/embedded view only; no scraping", "Situational weather visualization",
        "high", 60, "High", "2-4", 2, adapter="web_link_only"),
    _s("flightradar24", "Flightradar24", ["Aviation", "Real-Time Geospatial"],
        "partner_api", "Commercial API / licensed data access", "API plan credentials",
        "Plan-specific quotas; honor provider headers/contract",
        "Commercial/licensed", "API contract and redistribution restrictions require review",
        ["flight id", "callsign", "position", "altitude", "speed", "track"], "near-real-time",
        "official licensed API only", "Aviation situational awareness",
        "high", 88, "High", "3-5", 3, auth_env="FR24_API_TOKEN", adapter="partner_api"),
    _s("marinetraffic", "MarineTraffic", ["Maritime", "Real-Time Geospatial"],
        "partner_api", "Commercial API / licensed data access", "API credentials",
        "Plan-specific quotas; honor provider headers/contract",
        "Commercial/licensed", "Contractual data-use and redistribution limits",
        ["MMSI", "IMO", "position", "course", "speed", "vessel type"], "near-real-time",
        "official licensed API only", "Maritime traffic awareness",
        "high", 88, "High", "3-5", 2, auth_env="MARINETRAFFIC_API_KEY", adapter="partner_api"),
    _s("windy", "Windy", ["Weather", "Real-Time Geospatial"],
        "public_or_keyed_api", "Developer APIs available", "API key for keyed services",
        "Service-specific; verify current quota and headers",
        "Service-specific", "Map embeds/APIs and redistribution must follow Windy terms",
        ["forecast", "wind", "pressure", "temperature", "alerts"], "minutes-hours",
        "official API / map SDK", "Weather context and forecast layers",
        "medium", 88, "Medium", "2-4", 2, auth_env="WINDY_API_KEY", adapter="http_json"),
    _s("lightningmaps", "LightningMaps", ["Weather", "Real-Time Geospatial"],
        "web_only", "No documented general public API verified", "None",
        "Not published", "Site-specific", "Do not reverse-engineer or scrape undocumented interfaces",
        ["strike location", "time", "intensity/visualization"], "seconds-minutes",
        "deep-link only", "Lightning visualization",
        "high", 62, "High", "2-3", 2, adapter="web_link_only"),
    _s("usgs-earthquakes", "USGS Earthquake Feed", ["Real-Time Geospatial", "Earth Observation", "Environmental Intelligence"],
        "official_feed", "GeoJSON feeds", "None",
        "Reasonable use; feed service-specific limits should be honored",
        "US government/public-domain context; verify dataset terms", "Keep USGS attribution and feed URLs",
        ["magnitude", "depth", "time", "place", "geometry", "event id"], "minutes",
        "GeoJSON polling with ETag/conditional GET", "Earthquake detection and alerts",
        "low", 97, "Low", "1-2", 1,
        endpoint="https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", adapter="http_json", enabled=True),
    _s("submarine-cable-map", "Submarine Cable Map", ["Real-Time Geospatial", "Public Data"],
        "web_only", "No open API verified", "None", "Not published",
        "Commercial/licensed map data likely; verify", "No automated extraction unless licensed",
        ["cable route", "landing point", "operator", "status"], "periodic",
        "licensed dataset/manual reference only", "Critical undersea infrastructure context",
        "high", 70, "High", "3-5", 3, adapter="web_link_only"),
    _s("global-forest-watch", "Global Forest Watch", ["Environmental Intelligence", "Earth Observation", "Real-Time Geospatial"],
        "public_or_keyed_api", "Official data APIs available", "Token/key for services that require it",
        "Service-specific; respect documented quotas",
        "Dataset/provider-specific, often open with attribution", "Terms and dataset licenses vary by dataset",
        ["alerts", "forest change", "tree cover", "fires", "country/region geometry"], "daily-near-real-time",
        "official APIs plus cached datasets", "Deforestation and environmental monitoring",
        "medium", 91, "Medium", "2-4", 2, auth_env="GFW_API_TOKEN", adapter="http_json"),
    _s("worldometers", "Worldometer", ["Statistics", "Public Data"],
        "web_only", "No general public API verified", "None", "Not published",
        "Provider/site copyright and ToS", "No scraping for production; use upstream datasets",
        ["population", "economy", "health/statistics"], "daily/periodic",
        "manual/source-link only", "Fast reference statistics",
        "high", 63, "High", "2-3", 4, adapter="web_link_only"),
    _s("internet-live-stats", "Internet Live Stats", ["Statistics", "Public Data"],
        "web_only", "No general public API verified", "None", "Not published",
        "Provider/site terms", "Avoid scraping; prefer upstream measurement sources",
        ["internet users", "traffic/usage counters"], "near-real-time",
        "reference link only", "Public internet usage context",
        "high", 60, "High", "2-3", 4, adapter="web_link_only"),
    _s("openstreetmap", "OpenStreetMap", ["Real-Time Geospatial", "Public Data", "Knowledge Discovery"],
        "official_api", "OSM API and related ecosystem services", "None for public APIs; service policies apply",
        "Service-specific; use conservative rate controls",
        "ODbL 1.0 for OSM database; attribution required", "Tile/Nominatim/Overpass usage policies must be obeyed",
        ["nodes", "ways", "relations", "tags", "geometry", "changesets"], "seconds-days",
        "Overpass/Nominatim/API as appropriate; bulk via extracts", "Core geospatial basemap and entity context",
        "medium", 96, "Medium", "2-4", 1,
        endpoint="https://www.openstreetmap.org/api/0.6", adapter="osm_api", enabled=True),
    _s("atlas-obscura", "Atlas Obscura", ["Cultural Heritage", "Knowledge Discovery"],
        "web_only", "No public API verified", "None", "Not published",
        "Copyright/ToS apply", "Reference-only unless licensed",
        ["place title", "description", "location", "history"], "periodic",
        "deep-link/reference only", "Place-based cultural discovery",
        "high", 60, "High", "2-3", 4, adapter="web_link_only"),
    _s("nasa-eyes", "NASA Eyes", ["Space Intelligence", "Knowledge Discovery", "Education"],
        "interactive_app", "No general public API for the application itself", "None",
        "Not applicable: no hosted API", "Not applicable; use linked NASA data", "Do not screen-scrape the application",
        ["mission", "object", "trajectory", "visual context"], "event/data dependent",
        "reference/link integration", "Astronomy and mission visualization",
        "low", 82, "Medium", "1-3", 3, adapter="reference_only"),
    _s("stellarium", "Stellarium", ["Space Intelligence", "Education", "Knowledge Discovery"],
        "software_library", "Open-source astronomy software, not hosted API", "None",
        "Not applicable: no hosted API", "Open-source project; license of selected version applies",
        "Embedding/copying code or assets requires license compliance",
        ["star catalog", "sky coordinates", "object metadata"], "versioned",
        "local library/plugin/reference", "Astronomy and sky-position context",
        "medium", 90, "Medium", "2-4", 3, adapter="reference_only"),
    _s("nasa-apod", "NASA APOD", ["Space Intelligence", "Education", "Public Data"],
        "official_api", "Current APOD WordPress API; legacy API retires 2026-12-01",
        "No auth for exploration; API key recommended for regular use",
        "Default keyed API limit documented at 1,000 requests/hour; inspect response headers",
        "NASA usage terms; image-specific rights/credit apply", "Preserve NASA source and image credits",
        ["date", "title", "explanation", "media type", "image/video URL"], "daily",
        "official API with caching and conditional requests", "Daily astronomy imagery and metadata",
        "low", 98, "Low", "1-2", 1,
        endpoint="https://science.nasa.gov/wp-json/wp/v2/apod-basic", auth_env="NASA_API_KEY",
        adapter="nasa_apod", enabled=True),
    _s("nasa-image-library", "NASA Image Library", ["Space Intelligence", "Earth Observation", "Education"],
        "official_api", "NASA Images API", "None for public API",
        "Service-specific; reasonable use and caching", "NASA media terms plus asset-specific rights",
        "Preserve source center, title, credit and rights metadata",
        ["title", "description", "date created", "keywords", "media type", "asset URLs"], "daily/periodic",
        "official API + metadata cache", "Searchable NASA visual evidence",
        "low", 96, "Low", "1-2", 1, endpoint="https://images-api.nasa.gov/", adapter="nasa_images", enabled=True),
    _s("our-world-in-data", "Our World in Data", ["Public Data", "Statistics", "Education"],
        "official_api", "Chart Data API (CSV + metadata JSON)", "None",
        "Cache aggressively; no universal fixed general-purpose cap stated",
        "CC BY for OWID-produced work; upstream datasets keep upstream licenses",
        "Citation and third-party license checks are required",
        ["indicator", "entity", "year/date", "source", "metadata"], "daily/periodic",
        "CSV + metadata JSON with cache", "Cross-country statistical context",
        "low", 96, "Low", "1-2", 1, endpoint="https://ourworldindata.org/grapher/",
        adapter="owid_grapher", enabled=True),
    _s("gapminder", "Gapminder", ["Statistics", "Education", "Public Data"],
        "downloadable_data", "Public downloadable datasets; no general API verified", "None",
        "Not published", "Dataset-specific", "Use published downloads/repos; confirm dataset license",
        ["country", "indicator", "year", "value", "metadata"], "periodic",
        "versioned file import", "Long-run global indicators",
        "low", 86, "Low", "1-2", 4, adapter="file_import"),
    _s("information-is-beautiful", "Information Is Beautiful", ["Statistics", "Education", "Knowledge Discovery"],
        "web_only", "No general public API verified", "None", "Not published",
        "Visualization/data license varies by artifact", "Review license before redistribution",
        ["visualized datasets", "categories", "sources", "graphics"], "periodic",
        "reference/manual import only", "Human-friendly data discovery",
        "high", 66, "High", "2-3", 4, adapter="web_link_only"),
    _s("world-bank-open-data", "World Bank Open Data", ["Public Data", "Statistics", "Education"],
        "official_api", "Indicators API / downloads", "None for public APIs",
        "Service-specific reasonable use; cache requests",
        "World Bank open-data terms plus dataset-specific terms", "Preserve indicator/source metadata",
        ["indicator", "country", "date", "value", "source metadata"], "daily/periodic",
        "REST JSON + cached tables", "Macroeconomic and development context",
        "low", 97, "Low", "1-2", 1, endpoint="https://api.worldbank.org/v2/",
        adapter="http_json", enabled=True),
    _s("internet-archive", "Internet Archive", ["Historical Archives", "Knowledge Discovery", "Education"],
        "official_api", "Advanced Search and Metadata APIs", "None for public access",
        "Use reasonable request volume and caching",
        "Archive item licenses vary", "Preserve item identifier, creator, date and rights metadata",
        ["identifier", "title", "creator", "date", "collection", "rights"], "continuous/periodic",
        "AdvancedSearch/Metadata API", "Historical web and digitized collections",
        "low", 92, "Low", "1-3", 4, endpoint="https://archive.org/advancedsearch.php",
        adapter="internet_archive"),
    _s("project-gutenberg", "Project Gutenberg", ["Historical Archives", "Education", "Knowledge Discovery"],
        "downloadable_data", "Public-domain catalog/files; no general official JSON API verified",
        "None", "Not published", "Item/public-domain status varies by jurisdiction; Project Gutenberg terms apply",
        "Do not assume every file is public domain everywhere",
        ["ebook id", "title", "author", "language", "subjects", "release date"], "periodic",
        "catalog/feed/file import", "Historical text corpus",
        "medium", 84, "Medium", "2-4", 4, adapter="file_import"),
    _s("open-library", "Open Library", ["Historical Archives", "Education", "Knowledge Discovery"],
        "official_api", "Public JSON/YAML/RDF APIs", "None",
        "1 req/s default; identified apps up to 3 req/s per current guidance",
        "Open ecosystem; dataset/API licensing applies", "Not intended as high-traffic commercial backend; cache and identify client",
        ["work/edition id", "title", "author", "subjects", "identifiers", "publish date"], "continuous",
        "Search API + cached lookups", "Bibliographic discovery",
        "low", 97, "Low", "1-2", 4, endpoint="https://openlibrary.org/search.json",
        adapter="open_library", rate_limit_rps=1.0),
    _s("library-of-congress", "Library of Congress", ["Historical Archives", "Cultural Heritage", "Education"],
        "official_api", "loc.gov JSON/YAML API and additional machine-readable services",
        "None for loc.gov JSON API; some separate APIs use data.gov keys",
        "Service-specific; honor API guidance",
        "Collection/item rights vary; item-level rights are authoritative",
        "Preserve collection, rights and source URL metadata",
        ["title", "creator", "date", "subjects", "location", "rights", "resource URL"], "continuous/periodic",
        "loc.gov API with cache", "Authoritative cultural and historical source",
        "low", 96, "Low", "1-3", 4, endpoint="https://www.loc.gov/search/?fo=json",
        adapter="loc_json"),
    _s("europeana", "Europeana", ["Cultural Heritage", "Historical Archives", "Education"],
        "official_api", "Europeana APIs; OAI-PMH/SPARQL/dataset access", "Free API key",
        "Key/service-specific", "Europeana API plus individual item rights metadata apply",
        "Preserve rights statement, provider, collection and item id",
        ["title", "creator", "provider", "date", "type", "edm rights", "media URL"], "continuous",
        "REST API; OAI-PMH for scale", "European cultural heritage discovery",
        "medium", 94, "Medium", "2-4", 4, endpoint="https://api.europeana.eu/record/v2/",
        auth_env="EUROPEANA_API_KEY", adapter="europeana"),
    _s("dpla", "Digital Public Library of America", ["Cultural Heritage", "Historical Archives", "Education"],
        "official_api", "DPLA API", "API key",
        "Key-specific quotas; verify current developer limits",
        "Item rights originate with contributing institutions", "Preserve item/provider rights metadata",
        ["title", "creator", "date", "sourceResource", "rights", "provider"], "continuous/periodic",
        "REST API + cache", "US cultural heritage aggregation",
        "medium", 93, "Medium", "2-4", 4, endpoint="https://api.dp.la/v2/items",
        auth_env="DPLA_API_KEY", adapter="dpla"),
    _s("google-arts-culture", "Google Arts & Culture", ["Cultural Heritage", "Knowledge Discovery", "Education"],
        "web_only", "No general public API verified", "None", "Not published",
        "Google terms and partner-institution rights apply", "Reference/deep-link unless licensed integration exists",
        ["artwork", "institution", "artist", "era", "location"], "periodic",
        "deep-link/reference only", "Cultural context and visual discovery",
        "high", 70, "High", "2-3", 4, adapter="web_link_only"),
    _s("rijksmuseum", "Rijksmuseum", ["Cultural Heritage", "Historical Archives", "Education"],
        "official_api", "Rijksmuseum Collection API", "API key",
        "Published quota is key/service dependent; verify current guidance",
        "Museum API terms plus work-level rights", "Preserve creator, object id, rights and image attribution",
        ["object id", "title", "artist", "date", "materials", "web image URL"], "continuous",
        "REST API + metadata/image cache", "Primary-source art metadata",
        "medium", 95, "Low", "1-3", 4, endpoint="https://www.rijksmuseum.nl/api/en/collection",
        auth_env="RIJKSMUSEUM_API_KEY", adapter="rijksmuseum"),
    _s("wikiart", "WikiArt", ["Cultural Heritage", "Knowledge Discovery"],
        "web_only", "No public general API verified", "None", "Not published",
        "Artwork/image rights vary and site ToS apply", "Do not ingest/rehost images without rights review",
        ["artist", "title", "year", "movement", "image URL"], "periodic",
        "reference-only", "Art history discovery",
        "high", 68, "High", "2-3", 4, adapter="web_link_only"),
    _s("open-culture", "Open Culture", ["Education", "Cultural Heritage", "Knowledge Discovery"],
        "web_only", "No public general API verified", "None", "Not published",
        "Site content links to third-party media and rights", "Use as discovery/index, then ingest from original source",
        ["title", "creator", "resource URL", "subject"], "periodic",
        "reference/index only", "Open educational and cultural discovery",
        "medium", 72, "Medium", "1-2", 4, adapter="web_link_only"),
)

_BY_ID = {source.source_id: source for source in SOURCE_DEFINITIONS}


def get_source(source_id: str) -> SourceDefinition:
    try:
        return _BY_ID[source_id]
    except KeyError as exc:
        raise KeyError(f"unknown ARTEMIS OSINT source: {source_id}") from exc


def list_sources(*, phase: int | None = None) -> list[SourceDefinition]:
    sources = list(SOURCE_DEFINITIONS)
    if phase is not None:
        sources = [source for source in sources if source.phase == phase]
    return sources
